# Generated by Django 5.2 on 2025-04-08 11:42

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=50)),
                ("result", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "my_chess_style_task_result",
            },
        ),
    ]
