# Generated by Django 5.2 on 2025-04-08 18:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0003_taskresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
