# Generated by Django 5.2 on 2025-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0004_taskresult_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="stage",
            field=models.IntegerField(
                choices=[(1, "Game"), (2, "Chess Style")], default=1
            ),
        ),
    ]
