# Generated by Django 5.2 on 2025-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0008_alter_taskresult_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="pgnfileupload",
            name="source",
            field=models.IntegerField(
                choices=[(1, "CHESSDOTCOM"), (2, "LICHESS"), (3, "FILE")], default=3
            ),
        ),
    ]
