# Generated by Django 5.2 on 2025-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0011_drop_hstore_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChessOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eco_code", models.CharField(max_length=10)),
                ("full_name", models.CharField(max_length=255)),
                ("moves", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "my_chess_style_chess_opening",
            },
        ),
    ]
