# Generated by Django 5.2 on 2025-07-25 21:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0012_chessopening"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoastRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("include_roast", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
