# Generated by Django 5.2 on 2025-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("style_predictor", "0013_roastregister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresult",
            name="stage",
            field=models.IntegerField(
                choices=[
                    (1, "FILE_UPLOAD"),
                    (2, "GAME"),
                    (3, "ROASTING_USER"),
                    (4, "CHESS_STYLE"),
                ],
                default=1,
            ),
        ),
    ]
