# https://pre-commit.com
# https://pre-commit.com/hooks.html

default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.9"
    hooks:
      - id: ruff
        entry: ruff check --select I --fix
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
      - id: ruff
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.3"
    hooks:
      - id: bandit
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-export
      - id: uv-sync
  - repo: local
    hooks:
      - id: django_generate_openapi
        name: Generate openapi json file
        entry: uv run python manage.py generate_openapi
        language: system
        pass_filenames: false
        types: [python]
        stages: [post-commit]
        always_run: true
