[project]
name = "my-chess-style"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django>=5.2",
  "django-ninja>=1.4.0",
  "psycopg2>=2.9.10",
  "python-dotenv>=1.1.0",
]

[dependency-groups]
commit = ["pre-commit>=4.2.0"]
dev = ["pytest>=8.3.5", "ruff>=0.11.3"]
[tool.pytest.ini_options]
pythonpath = ["."]
