GET_CHESS_COM_TASK: str = "pgn_get_chess_com_games_by_user"
GET_LICHESS_TASK: str = "pgn_get_lichess_games_by_user"
GET_FILE_GAMES_TASK: str = "pgn_get_games_from_file"
ANALYZE_GAMES_TASK: str = "pgn_analyze_games"
CHESS_STYLE_TASK: str = "pgn_determine_chess_playing_style"
WHITE_WIN: str = "1-0"
BLACK_WIN: str = "0-1"
DRAW: str = "1/2-1/2"
