apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: my-chess-style-app
data:
  POSTGRES_DB: my_chess_style_db
  PG_PORT: 5429

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-chess-style-app
type: Opaque
data:
  POSTGRES_USER: ZDFyM2N0MHIK
  POSTGRES_PASSWORD: RnJlZUxvYWRlcjEK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: my-chess-style-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: my_chess_style_pg
          image: postgres:17.5
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-chess-style-app
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-service-port
      protocol: TCP
      port: 5429
      targetPort: 5432
